### ISSUE TITLE
Allow pointings file to contain pulsar names as well as RA/Dec pairs

### ISSUE THREAD

**Issue by robotopia** [CIRA-Pulsars-and-Transients-Group/vcsbeam#11]
Instead of only allowing the format
```
HH:MM:SS.S  DD:MM:SS.S
HH:MM:SS.S  DD:MM:SS.S
...
```
also allow pulsar names to be given, e.g.
```
PSR B0031-07
PSR J0437-4715
...
```
This will require using `psrcat` as a dependency.

**Comment by NickSwainston** [comment]
Could you also accept pointings in the following format
```
HH:MM:SS.S_DD:MM:SS.S
HH:MM:SS.S_DD:MM:SS.S
...
```
As that's what I do in mwa_search

**Comment by robotopia** [comment]
I could, but not straightforwardly. The parser counts whitespace-separated "words" to figure out how many pointings there are. Would it be easier to generalise the formats that mwa_search can output?

**Comment by bwmeyers** [comment]
Personally, I don't think this is an issue any more. Worst case scenario is that there's a small bash command to run on a file containing `_` separated coordinates, so I'm going to close this.
