### ISSUE TITLE
Typo on matrix on the bottom for calibration page 

### ISSUE THREAD

**Issue by marcinsokolowski** [CIRA-Pulsars-and-Transients-Group/vcsbeam#20]
In https://cira-pulsars-and-transients-group.github.io/vcsbeam/calibration.html
Last line has a product of matrix B and P , but elements of matrix P are Bs with only one P.
[https://cira-pulsars-and-transients-group.github.io/vcsbeam/calibration.html](url)

**Comment by robotopia** [comment]
Fixed in df8d29e.
