### ISSUE TITLE
Real/imag placement test with offline pfb

### ISSUE THREAD

**Issue by robotopia** [CIRA-Pulsars-and-Transients-Group/vcsbeam#3]
A recent change in v3.0 was that a matrix conjugation operation was removed, and the order in which the real and imaginary parts of the complex voltages samples are read in was swapped (these two operations effectively cancel each other, constituting two reflections in the complex plane, equivalent to a single rotation). However, in order to keep the code self-consistent, this also included a change to the way the offline fine PFB writes out the fine-channelised complex samples. It remains to be seen whether this breaks the full pipeline for processing MWAX data.

**Comment by bwmeyers** [comment]
Is this still true? (Given we've just been exploring the "guts" of the PFB code.)

**Comment by robotopia** [comment]
I still don't understand it myself, but perhaps a more pragmatic use for this issue is to focus on developing unit tests for these bits of code rather than "trying to understand it".

**Comment by bwmeyers** [comment]
I'd agree. I might close this then, and make a new issue specifically for unit testing.
