### ISSUE TITLE
HIP VCSBeam: Determine which kernels need to be altered

### ISSUE THREAD

**Issue by bwmeyers** [CIRA-Pulsars-and-Transients-Group/vcsbeam#38]
Our first steps should be to identify which parts of VCSBeam are (critically) required to be GPU-vendor agnostic. Luckily, we don't use any specific low-level instructions, so this should be a reasonably easy task.

**Comment by marcinsokolowski** [comment]
From what I have looked and started to modify the code (branch main_gpu) there is no need for changes in the kernels except for some types (cuComplex to macro gpuComplex) and function calls e.g. cuCadd to macro gpuCadd

**Comment by bwmeyers** [comment]
This has been completed and drafted in branch `main_gpu_bwm` which is acting as the "base" branch for the Pawsey Uptake project work. https://github.com/CIRA-Pulsars-and-Transients-Group/vcsbeam/tree/main_gpu_bwm
