### ISSUE TITLE
Reduced snr for the pointing position on the first line of the pointing file 

### ISSUE THREAD

**Issue by mengyaoxue** [CIRA-Pulsars-and-Transients-Group/vcsbeam#59]
When doing beamform, the pointing position on the first line of the pointing file will have significantly lower snr than expected, while other lines in the pointing file all look fine.
I had some examples in /scratch/mwavcs/xuemy/1206977296/vb0test and /scratch/mwavcs/xuemy/1206977296/vb0test2
The corresponding painting files are /scratch/mwavcs/xuemy/1206977296/pointings_0_test.txt and /scratch/mwavcs/xuemy/1206977296/pointings_0_test2.txt
![图片](https://github.com/user-attachments/assets/4ee21e66-6103-429e-89b5-3ca5c638370e)

**Comment by chiamintan** [comment]
![J0034_beamform_test](https://github.com/user-attachments/assets/889f08b1-c2d9-496b-8dd3-12a310933e54)
I tested out what Mengyao have seen with some recent 5 min test J0034 data that we have and I see that large chunk of the frequencies are missing on the first pointing (top left) and one subband is missing on 2nd/3rd pointing and all data is there on the 4th pointing (bottom right). These data are processed on garrawarla and I would like to run the beam former on setonix and/or NT to see if I get the same thing

**Comment by fxzjshm** [comment]
We've also tested on a HIP-based device and in our case the 1st and 2nd beams are affected; 
dumping output S array shows same result (at least for the first block)

Pointings:
```
12:24:24.58 -64:07:28.62
12:24:24.58 -64:07:28.61
12:24:24.58 -64:07:28.63
12:24:24.57 -64:07:28.62
12:24:24.59 -64:07:28.62
```

Result:

![4](https://github.com/user-attachments/assets/dd14ff9b-6dae-4614-a627-c303904815fc)

**Comment by robotopia** [comment]
It's starting to sound like a race condition in the MPI which is responsible for splicing the coarse channels back together into a single FITS file. If so, a workaround might be to run 24 separate jobs (one for each channel) and splice them together afterwards (which is how it used to be done, back in VCSTools).

**Comment by fxzjshm** [comment]
in #60  I've fixed config caching in `vmCalcB` and this patch fixes folding in our local test environment in NAOC, as shown in figure below.
But our test environment has only 1 node so cannot test MPI over multiple nodes.

![7](https://github.com/user-attachments/assets/32bb8e72-308a-4097-bb1a-1b6b8c128f6d)

**Comment by bwmeyers** [comment]
Okay, I will deploy this branch today on Garrawarla to try.

**Comment by bwmeyers** [comment]
This appears to have fixed the multi-pointing config issues, but I'm still waiting on confirmation from @mengyaoxue

**Comment by mengyaoxue** [comment]
Hi Brad, I confirm that #60 has fixed the multi-pointing config issues.
