### ISSUE TITLE
Check whether the PQ phase correction should be applied to P or Q

### ISSUE THREAD

**Issue by robotopia** [CIRA-Pulsars-and-Transients-Group/vcsbeam#7]

**Comment by bwmeyers** [comment]
I'm guessing this can be closed? Is the "Invalid" flag w.r.t. the issue? We can nominally re-open an issue if/when this becomes a priority.

**Comment by robotopia** [comment]
This can be closed. In hindsight, all efforts to get the polarisations correct should be done at the calibration stage, and applied to the calibration solutions, instead of applying any corrections to the voltages themselves. We should deprecate the relevant command line options.
