### ISSUE TITLE
Model the calibration solutions

### ISSUE THREAD

**Issue by robotopia** [CIRA-Pulsars-and-Transients-Group/vcsbeam#8]
Develop tools to model the calibration solutions, with a view to building up a database of calibration models that can be used to explore the stability of the MWA

**Comment by bwmeyers** [comment]
Still useful/relevant to VCSBeam? Or does this sort of belong as a `hyperbeam` utility?

**Comment by robotopia** [comment]
Either `hyperbeam` or something to be offloaded to the MWA ops team generally, but you're right: this is definitely out of scope for VCSBeam. I'm officially out of the game on this issue, so I leave it to you, @bwmeyers, to find a new home for this issue, if you feel it's worth it, and then I'm happy to remove it from here.

**Comment by bwmeyers** [comment]
I know that the idea is the ops team will have a server (`calvin`) that does online/real-time/on-site calibration for MWAX, and my understanding is that it's nearly mature. Not exactly the same issue, but it does seem like a `hyperbeam` capability, albeit a bit niche? For now, let's leave this open, but I'll tag it appropriately.

**Comment by bwmeyers** [comment]
Closing this now, as it's not within the remit of VCSBeam (but the ideal of modelling calibration solutions to "idealise" them across the band is something other teams do/tried before, so we can explore that option with them).
